class: App\User
title: Users
icon: fa fa-users
sort:
  field: name
  order: asc
list:
  id: ID
  name: Name
  email: E-Mail
fields:
  name:
    label: Name
    type: text
    placeholder: John Doe
    validate: required
  email:
    label: E-Mail
    type:  text
    placeholder: email@somewebsite.com
    validate: required|email
